[build]
  # base = "frontend" 
  command = "npm run build" # Or yarn build, or whatever your build command is
  publish = "frontend/dist" # Or frontend/build, or whatever your build output directory is